### ISSUE TITLE
Add publication

### ISSUE THREAD

**Issue by jgvictores** [ssantamaria94/roboasset-web#1]
Accepted a while ago, will be presented in these days (so we'll soon have the DOI), cites Roboasset!

APA style:
Fernandez-Fernandez, R., Aggravi, M., Giordano, P., Victores, J.G., & Pacchierotti, C. (2022, May). Neural Style Transfer with Twin-Delayed DDPG for Shared Control of Robotic Manipulators. In IEEE International Conference on Robotics and Automation (ICRA).

bibtex:
@inproceedings{fernandez2022neural,
  title={Neural Style Transfer with Twin-Delayed DDPG for Shared Control of Robotic Manipulators},
  author={Fernandez-Fernandez, Raul and Aggravi, Marco and Giordano, Paolo and Victores, Juan and Pacchierotti, Claudio},
  booktitle={IEEE International Conference on Robotics and Automation (ICRA)},
  year={2022}
}

**Comment by ssantamaria94** [comment]
Done!
